"""initial ProbX schema

Revision ID: 3b35aa1fb6a9
Revises:
Create Date: 2026-07-12 16:31:49.310273
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3b35aa1fb6a9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chain_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tx_hash", sa.String(length=64), nullable=True),
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=True),
        sa.Column("submitted_by", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("block_height", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chain_transactions")),
        sa.UniqueConstraint("payload_hash", name=op.f("uq_chain_transactions_payload_hash")),
    )
    op.create_index(
        op.f("ix_chain_transactions_intent"), "chain_transactions", ["intent"], unique=False
    )
    op.create_index(
        op.f("ix_chain_transactions_market_id"), "chain_transactions", ["market_id"], unique=False
    )
    op.create_index(
        op.f("ix_chain_transactions_status"), "chain_transactions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_chain_transactions_submitted_by"),
        "chain_transactions",
        ["submitted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chain_transactions_tx_hash"), "chain_transactions", ["tx_hash"], unique=True
    )
    op.create_table(
        "market_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("creator_payment_credential", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.String(length=280), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("trading_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("yes_criteria", sa.Text(), nullable=False),
        sa.Column("primary_source", sa.String(length=1024), nullable=False),
        sa.Column("backup_source", sa.String(length=1024), nullable=True),
        sa.Column("invalid_market_rule", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("normalized_statement", sa.String(length=280), nullable=True),
        sa.Column("normalized_yes_criteria", sa.Text(), nullable=True),
        sa.Column("normalized_primary_source", sa.String(length=1024), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_drafts")),
    )
    op.create_index(op.f("ix_market_drafts_category"), "market_drafts", ["category"], unique=False)
    op.create_index(
        op.f("ix_market_drafts_creator_payment_credential"),
        "market_drafts",
        ["creator_payment_credential"],
        unique=False,
    )
    op.create_index(op.f("ix_market_drafts_status"), "market_drafts", ["status"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_created_at"), "outbox_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_topic"), "outbox_events", ["topic"], unique=False)
    op.create_table(
        "resolutions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column("evidence_uri", sa.String(length=1024), nullable=False),
        sa.Column("quorum_reached", sa.Boolean(), nullable=False),
        sa.Column("resolver_signatures", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolutions")),
    )
    op.create_index(op.f("ix_resolutions_market_id"), "resolutions", ["market_id"], unique=True)
    op.create_table(
        "simulation_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("virtual_personas", sa.Integer(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("generated_actions", sa.BigInteger(), nullable=False),
        sa.Column("accepted_actions", sa.BigInteger(), nullable=False),
        sa.Column("rejected_actions", sa.BigInteger(), nullable=False),
        sa.Column("real_preprod_transactions", sa.Integer(), nullable=False),
        sa.Column("last_tick_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("strategies", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_state")),
    )
    op.create_table(
        "wallet_challenges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("network", sa.String(length=16), nullable=False),
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_challenges")),
        sa.UniqueConstraint("nonce_hash", name=op.f("uq_wallet_challenges_nonce_hash")),
    )
    op.create_index(
        op.f("ix_wallet_challenges_address"), "wallet_challenges", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_challenges_expires_at"), "wallet_challenges", ["expires_at"], unique=False
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("payment_credential", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("network", sa.String(length=16), nullable=False),
        sa.Column("auth_mode", sa.String(length=16), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("last_authenticated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=True)
    op.create_index(
        op.f("ix_wallets_payment_credential"), "wallets", ["payment_credential"], unique=True
    )
    op.create_table(
        "markets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=True),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("creator_payment_credential", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.String(length=280), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("trading_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("yes_criteria", sa.Text(), nullable=False),
        sa.Column("primary_source", sa.String(length=1024), nullable=False),
        sa.Column("backup_source", sa.String(length=1024), nullable=True),
        sa.Column("invalid_market_rule", sa.Text(), nullable=False),
        sa.Column("terms_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("is_simulation", sa.Boolean(), nullable=False),
        sa.Column("opening_yes_count", sa.Integer(), nullable=False),
        sa.Column("opening_no_count", sa.Integer(), nullable=False),
        sa.Column("opening_poll_root", sa.String(length=64), nullable=True),
        sa.Column("yes_probability", sa.Integer(), nullable=True),
        sa.Column("liquidity_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("minimum_liquidity_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("user_collateral_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("volume_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("lp_fees_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("yes_liability_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("no_liability_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("resolution_outcome", sa.String(length=8), nullable=True),
        sa.Column("evidence_uri", sa.String(length=1024), nullable=True),
        sa.Column("chain_state_reference", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["market_drafts.id"],
            name=op.f("fk_markets_draft_id_market_drafts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint("draft_id", name=op.f("uq_markets_draft_id")),
    )
    op.create_index(op.f("ix_markets_category"), "markets", ["category"], unique=False)
    op.create_index(
        op.f("ix_markets_creator_payment_credential"),
        "markets",
        ["creator_payment_credential"],
        unique=False,
    )
    op.create_index(op.f("ix_markets_is_simulation"), "markets", ["is_simulation"], unique=False)
    op.create_index(op.f("ix_markets_slug"), "markets", ["slug"], unique=True)
    op.create_index(op.f("ix_markets_status"), "markets", ["status"], unique=False)
    op.create_index(
        op.f("ix_markets_trading_deadline"), "markets", ["trading_deadline"], unique=False
    )
    op.create_table(
        "liquidity_contributions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("owner_payment_credential", sa.String(length=64), nullable=False),
        sa.Column("amount_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("lp_units", sa.BigInteger(), nullable=False),
        sa.Column("receipt_reference", sa.String(length=255), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_liquidity_contributions_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_liquidity_contributions")),
    )
    op.create_index(
        op.f("ix_liquidity_contributions_market_id"),
        "liquidity_contributions",
        ["market_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_liquidity_contributions_owner_payment_credential"),
        "liquidity_contributions",
        ["owner_payment_credential"],
        unique=False,
    )
    op.create_table(
        "market_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("yes_probability", sa.Integer(), nullable=True),
        sa.Column("volume_delta_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("chain_tx_hash", sa.String(length=64), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_market_events_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_events")),
    )
    op.create_index(
        op.f("ix_market_events_chain_tx_hash"), "market_events", ["chain_tx_hash"], unique=False
    )
    op.create_index(
        op.f("ix_market_events_event_type"), "market_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_market_events_market_id"), "market_events", ["market_id"], unique=False
    )
    op.create_index(
        "ix_market_events_market_recorded",
        "market_events",
        ["market_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "opening_forecasts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("payment_credential", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=3), nullable=False),
        sa.Column("signed_message", sa.Text(), nullable=False),
        sa.Column("cose_sign1", sa.Text(), nullable=False),
        sa.Column("cose_key", sa.Text(), nullable=False),
        sa.Column("verification_mode", sa.String(length=16), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("leaf_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_opening_forecasts_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opening_forecasts")),
        sa.UniqueConstraint(
            "market_id", "payment_credential", name="uq_opening_forecast_market_wallet"
        ),
    )
    op.create_index(
        "ix_opening_forecasts_market_created",
        "opening_forecasts",
        ["market_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opening_forecasts_market_id"), "opening_forecasts", ["market_id"], unique=False
    )
    op.create_index(
        op.f("ix_opening_forecasts_payment_credential"),
        "opening_forecasts",
        ["payment_credential"],
        unique=False,
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("owner_payment_credential", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=3), nullable=False),
        sa.Column("shares", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("entry_probability", sa.Integer(), nullable=False),
        sa.Column("maximum_payout_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("estimated_value_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("realized_pnl_lovelace", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("position_reference", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_positions_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(op.f("ix_positions_is_simulated"), "positions", ["is_simulated"], unique=False)
    op.create_index(op.f("ix_positions_market_id"), "positions", ["market_id"], unique=False)
    op.create_index(
        op.f("ix_positions_owner_payment_credential"),
        "positions",
        ["owner_payment_credential"],
        unique=False,
    )
    op.create_index(
        "ix_positions_owner_status",
        "positions",
        ["owner_payment_credential", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_positions_status"), "positions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_positions_status"), table_name="positions")
    op.drop_index("ix_positions_owner_status", table_name="positions")
    op.drop_index(op.f("ix_positions_owner_payment_credential"), table_name="positions")
    op.drop_index(op.f("ix_positions_market_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_is_simulated"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_opening_forecasts_payment_credential"), table_name="opening_forecasts")
    op.drop_index(op.f("ix_opening_forecasts_market_id"), table_name="opening_forecasts")
    op.drop_index("ix_opening_forecasts_market_created", table_name="opening_forecasts")
    op.drop_table("opening_forecasts")
    op.drop_index("ix_market_events_market_recorded", table_name="market_events")
    op.drop_index(op.f("ix_market_events_market_id"), table_name="market_events")
    op.drop_index(op.f("ix_market_events_event_type"), table_name="market_events")
    op.drop_index(op.f("ix_market_events_chain_tx_hash"), table_name="market_events")
    op.drop_table("market_events")
    op.drop_index(
        op.f("ix_liquidity_contributions_owner_payment_credential"),
        table_name="liquidity_contributions",
    )
    op.drop_index(
        op.f("ix_liquidity_contributions_market_id"), table_name="liquidity_contributions"
    )
    op.drop_table("liquidity_contributions")
    op.drop_index(op.f("ix_markets_trading_deadline"), table_name="markets")
    op.drop_index(op.f("ix_markets_status"), table_name="markets")
    op.drop_index(op.f("ix_markets_slug"), table_name="markets")
    op.drop_index(op.f("ix_markets_is_simulation"), table_name="markets")
    op.drop_index(op.f("ix_markets_creator_payment_credential"), table_name="markets")
    op.drop_index(op.f("ix_markets_category"), table_name="markets")
    op.drop_table("markets")
    op.drop_index(op.f("ix_wallets_payment_credential"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_wallet_challenges_expires_at"), table_name="wallet_challenges")
    op.drop_index(op.f("ix_wallet_challenges_address"), table_name="wallet_challenges")
    op.drop_table("wallet_challenges")
    op.drop_table("simulation_state")
    op.drop_index(op.f("ix_resolutions_market_id"), table_name="resolutions")
    op.drop_table("resolutions")
    op.drop_index(op.f("ix_outbox_events_topic"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_created_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_market_drafts_status"), table_name="market_drafts")
    op.drop_index(op.f("ix_market_drafts_creator_payment_credential"), table_name="market_drafts")
    op.drop_index(op.f("ix_market_drafts_category"), table_name="market_drafts")
    op.drop_table("market_drafts")
    op.drop_index(op.f("ix_chain_transactions_tx_hash"), table_name="chain_transactions")
    op.drop_index(op.f("ix_chain_transactions_submitted_by"), table_name="chain_transactions")
    op.drop_index(op.f("ix_chain_transactions_status"), table_name="chain_transactions")
    op.drop_index(op.f("ix_chain_transactions_market_id"), table_name="chain_transactions")
    op.drop_index(op.f("ix_chain_transactions_intent"), table_name="chain_transactions")
    op.drop_table("chain_transactions")
    # ### end Alembic commands ###
